"""Initial application schema. LangGraph owns its separate checkpoint schema."""
from alembic import op
import sqlalchemy as sa

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('customer_email', sa.String(length=254), nullable=False),
    sa.Column('preferred_brands', sa.JSON(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('original_total_paisa', sa.Integer(), nullable=False),
    sa.Column('final_total_paisa', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('manual_decision', sa.String(length=20), nullable=True),
    sa.Column('had_shortage', sa.Boolean(), nullable=False),
    sa.Column('recovered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=False),
    sa.Column('substitution_group', sa.String(length=100), nullable=False),
    sa.Column('price_paisa', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.CheckConstraint('price_paisa > 0'),
    sa.CheckConstraint('stock >= 0'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_substitution_group'), 'products', ['substitution_group'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_order_id'), 'audit_events', ['order_id'], unique=False)
    op.create_table('jobs',
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('pending', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_jobs_pending'), 'jobs', ['pending'], unique=False)
    op.create_table('order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('original_product_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_paisa', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Boolean(), nullable=False),
    sa.CheckConstraint('quantity > 0'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['original_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_lines_order_id'), 'order_lines', ['order_id'], unique=False)
    op.create_table('outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_key', sa.String(length=100), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key')
    )
    op.create_index(op.f('ix_outbox_order_id'), 'outbox', ['order_id'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('unit_price_paisa', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('held', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['order_lines.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_id')
    )
    op.create_index(op.f('ix_offers_expires_at'), 'offers', ['expires_at'], unique=False)
    op.create_index(op.f('ix_offers_order_id'), 'offers', ['order_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offers_order_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_expires_at'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_outbox_order_id'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_order_lines_order_id'), table_name='order_lines')
    op.drop_table('order_lines')
    op.drop_index(op.f('ix_jobs_pending'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_audit_events_order_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_products_substitution_group'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
