import {useEffect,useRef,useState} from 'react';
import {Basket,ArrowRight,X,PlugsConnected,WarningCircle,CheckCircle,Eye,ShieldCheck,Lightning} from '@phosphor-icons/react';
import {Chart,LineController,LineElement,PointElement,CategoryScale,LinearScale} from 'chart.js';
import {initialDemo,metricsFor,transition,money,statusLabels,uid} from './demo';
import '@fontsource/inter/400.css';import '@fontsource/inter/500.css';import '@fontsource/inter/600.css';import '@fontsource/inter/700.css';import '@fontsource/inter/800.css';
Chart.register(LineController,LineElement,PointElement,CategoryScale,LinearScale);
function Pipeline({active}){
 const ref=useRef(null);
 useEffect(()=>{const c=new Chart(ref.current,{type:'line',data:{labels:['Intake','','Fraud check','','Inventory','','Negotiation','','Resolution'],datasets:[{data:[45,58,46,35,52,72,63,26,42],borderColor:'#7a386f',borderWidth:2,borderDash:[7,7],tension:.45,pointRadius:[0,0,4,0,4,0,0,5,0],pointBackgroundColor:['#fa315f','#fa315f','#55bca0','#55bca0','#6274ff','#6274ff','#6274ff','#e9447e','#e9447e'],segment:{borderColor:ctx=>['#e62a67','#a63b98','#5350de','#5362ec','#5877df','#4ba890','#647376','#b23979'][ctx.p0DataIndex]}}]},options:{responsive:true,maintainAspectRatio:false,animation:{duration:matchMedia('(prefers-reduced-motion: reduce)').matches?0:600},plugins:{legend:{display:false},tooltip:{enabled:false}},scales:{x:{display:false},y:{display:false,min:0,max:100}}}});return()=>c.destroy();},[]);
 return <section className="panel pipeline" aria-label="Order processing stages"><h2><span className="accent pink"/>Live Order Pipeline</h2><div className="wave"><canvas ref={ref} role="img" aria-label="Illustrative path through intake, fraud check, inventory, negotiation and resolution"/></div><div className="stages">{['INTAKE','FRAUD CHECK','INVENTORY','NEGOTIATION','RESOLUTION'].map((n,i)=><div key={n} className={'stage '+(active===i?'current':'')} style={{'--stage-color':['#f12b5d','#5867ff','#51b798','#c54aa1','#e0b929'][i]}}><span className="stage-dot"/>{n}</div>)}</div><span className="pipeline-caption">{active===null?'Ready for the next grocery order':'Processing grocery order…'}</span></section>;
}
function Modal({title,children,onClose}){
 const ref=useRef(null),previous=useRef(document.activeElement);
 useEffect(()=>{const d=ref.current;d.showModal();const p=previous.current;return()=>{d.close();p?.focus();};},[]);
 return <dialog ref={ref} className="modal" onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}}><div className="modal-head"><h2>{title}</h2><button className="icon-btn" onClick={onClose} aria-label="Close dialog"><X size={20}/></button></div>{children}</dialog>;
}
export function App(){
 const [demo,setDemo]=useState(initialDemo),[live,setLive]=useState(null),[mode,setMode]=useState('demo'),[key,setKey]=useState(''),[candidateKey,setCandidateKey]=useState('');
 const [email,setEmail]=useState(''),[product,setProduct]=useState('1'),[quantity,setQuantity]=useState(1),[risk,setRisk]=useState('.1'),[payment,setPayment]=useState('prepaid');
 const [busy,setBusy]=useState(false),[connecting,setConnecting]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[modal,setModal]=useState(null),[stage,setStage]=useState(null),[now,setNow]=useState(new Date()),[health,setHealth]=useState(true);
 const timer=useRef([]),pendingRequest=useRef(null),modeRef=useRef(mode),polling=useRef(false);
 const data=mode==='live'&&live?live:demo,metrics=data.metrics||metricsFor(data.orders),selectedProduct=data.products.find(p=>p.id===Number(product)),selectedOrder=data.orders.find(o=>o.id===modal?.id);
 const call=async(path,options={},useKey=key)=>{const r=await fetch(path,{...options,headers:{'Content-Type':'application/json','X-API-Key':useKey,...options.headers}});let result;try{result=await r.json();}catch{throw new Error('The API is unavailable. Open this dashboard through FastAPI to connect.');}if(!r.ok)throw new Error(typeof result.detail==='string'?result.detail:'Please check the order details and try again.');return result;};
 const refresh=async()=>{if(polling.current||modeRef.current!=='live')return;polling.current=true;try{const result=await call('/dashboard');if(modeRef.current==='live'){setLive(result);setHealth(true);}}catch(e){if(modeRef.current==='live'){setHealth(false);setError(e.message);}}finally{polling.current=false;}};
 useEffect(()=>{modeRef.current=mode;},[mode]);
 useEffect(()=>{const id=setInterval(()=>setNow(new Date()),1000);return()=>{clearInterval(id);timer.current.forEach(clearTimeout);};},[]);
 useEffect(()=>{if(mode!=='live')return;refresh();const id=setInterval(refresh,3000);return()=>clearInterval(id);},[mode,key]);
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(id);},[notice]);
 const animate=()=>{setStage(0);[1,2,3,4].forEach((s,i)=>timer.current.push(setTimeout(()=>setStage(s),(i+1)*240)));timer.current.push(setTimeout(()=>setStage(null),1700));};
 const connect=async e=>{e.preventDefault();setConnecting(true);setError('');try{const r=await call('/dashboard',{},candidateKey);setLive(r);setKey(candidateKey);setMode('live');setHealth(true);setProduct(String(r.products[0]?.id||''));setModal(null);setCandidateKey('');setNotice('Connected to your OrderOps database.');}catch(e){setError(e.message);}finally{setConnecting(false);}};
 const create=async e=>{e.preventDefault();if(busy||!selectedProduct)return;setBusy(true);setError('');animate();const body={external_id:pendingRequest.current||uid(),customer_email:email,risk_score:Number(risk),payment_method:payment,preferred_brands:[],items:[{product_id:Number(product),quantity:Number(quantity)}]};pendingRequest.current=body.external_id;
  if(mode==='live'){try{await call('/orders',{method:'POST',body:JSON.stringify(body)});pendingRequest.current=null;setNotice('Order queued. The worker will process it shortly.');await refresh();}catch(e){setError(e.message);}finally{setBusy(false);}return;}
  const id=uid(),o={id,display_id:'#'+(demo.orders.length+1),customer_email:email,risk_score:Number(risk),payment_method:payment,status:'processing',original_total_paisa:selectedProduct.price_paisa*quantity,final_total_paisa:selectedProduct.price_paisa*quantity,had_shortage:false,recovered:false,created_at:new Date().toISOString(),items:[{product_id:Number(product),original_product_id:Number(product),name:selectedProduct.name,quantity:Number(quantity),unit_price_paisa:selectedProduct.price_paisa,reserved:false}],offers:[]};
  setDemo(s=>({...s,orders:[o,...s.orders],events:[{id:uid(),order_id:id,kind:'intake',created_at:new Date().toISOString(),payload:{text:`${o.display_id} · Received ${quantity} × ${selectedProduct.name}. Checking risk and stock.`}},...s.events]}));
  timer.current.push(setTimeout(()=>{setDemo(s=>transition(s,{type:'process',id}));setBusy(false);pendingRequest.current=null;setNotice('Demo order processed. See its status in the orders table.');},1300));
 };
 const act=async(type)=>{if(!selectedOrder||busy)return;setBusy(true);setError('');const id=selectedOrder.id;try{if(mode==='demo')setDemo(s=>transition(s,{id,type}));else if(selectedOrder.status==='manual_review')await call(`/orders/${id}/audit`,{method:'POST',body:JSON.stringify({decision:type==='approve'?'approve':'reject'})});else{const a=selectedOrder.offers.find(x=>x.status==='pending'),outbox=await call(`/orders/${id}/outbox`),msg=outbox.find(x=>x.kind==='offer_email'&&x.payload.offer_id===a.id);if(!msg)throw new Error('Offer message is not available yet.');await call(`/offers/${a.id}/reply`,{method:'POST',body:JSON.stringify({token:msg.payload.token,decision:type})});}if(mode==='live')await refresh();setModal(null);setNotice(type==='reject'?'Decision recorded. Cancellation/refund processing will follow.':'Approval recorded. The order will continue through the pipeline.');animate();}catch(e){setError(e.message);}finally{setBusy(false);}};
 const offer=selectedOrder?.offers?.find(x=>x.status==='pending'),offeredLine=selectedOrder?.items?.find(x=>x.id===offer?.line_id)||selectedOrder?.items?.[0],newTotal=offer&&offeredLine?selectedOrder.final_total_paisa-offeredLine.quantity*offeredLine.unit_price_paisa+offeredLine.quantity*offer.unit_price_paisa:0,resetField=setter=>e=>{pendingRequest.current=null;setter(e.target.value);};
 return <><header className="topbar"><a className="brand" href="#" aria-label="OrderOps AI home"><Basket size={19} weight="duotone"/><b>OrderOps</b><span>AI</span><span className="edition">GROCERY</span></a><div className="header-right"><button className={'connection '+(mode==='live'&&!health?'offline':'')} onClick={()=>{setError('');setModal({kind:'connect'});}}><span/>{mode==='demo'?'DEMO MODE':health?'API CONNECTED':'API OFFLINE'}</button><time>{now.toLocaleTimeString('en-GB')}</time></div></header>
 <main><section className="hero"><h1>Autonomous <em>Grocery Order Triage</em><br/> &amp; Resolution Agent</h1><p>Every grocery order deserves a second chance. Check stock, offer alternatives, recover revenue.</p></section>
 <div className="metrics"><div className="metric pink"><strong>{metrics.orders}</strong><span>TOTAL ORDERS</span></div><div className="metric green"><strong>{metrics.ready}</strong><span>READY TO FULFILL</span></div><div className="metric blue"><strong><small>Rs.</small> {Math.round(metrics.recovered_value_paisa/100).toLocaleString()}</strong><span>REVENUE RECOVERED</span></div><div className="metric purple"><strong>{metrics.refunds}</strong><span>REFUNDS PENDING</span></div></div>
 <Pipeline active={stage}/>
 <div className="workspace"><section className="panel create-panel"><h2><span className="accent blue"/>Create Test Order</h2><form onSubmit={create}><label>CUSTOMER EMAIL<input aria-label="Customer email" type="email" placeholder="customer@example.com" required value={email} onChange={resetField(setEmail)} maxLength={254}/></label><label>GROCERY PRODUCT<select aria-label="Grocery product" value={product} onChange={resetField(setProduct)} required>{data.products.map(p=><option key={p.id} value={p.id}>{p.name} — {money(p.price_paisa)}</option>)}</select></label><div className={'stock-info '+(selectedProduct?.stock?'green-text':'amber-text')}>{selectedProduct?.stock?`${selectedProduct.stock} units available`:'Out of stock · agent will look for an alternative'}</div><div className="form-row"><label>QUANTITY<input aria-label="Quantity" type="number" min="1" max="100" step="1" required value={quantity} onChange={resetField(setQuantity)}/></label><label>PAYMENT<select aria-label="Payment" value={payment} onChange={resetField(setPayment)}><option value="prepaid">Prepaid</option><option value="cod">Cash on delivery</option></select></label></div><label>TEST RISK PROFILE<select aria-label="Test risk profile" value={risk} onChange={resetField(setRisk)}><option value=".1">Low risk · 0.10</option><option value=".5">Medium risk · 0.50</option><option value=".92">High risk · 0.92</option></select></label><div className="order-total"><span>Order total</span><strong>{money((selectedProduct?.price_paisa||0)*quantity)}</strong></div><button className="dispatch" disabled={busy||!selectedProduct}>{busy?'Processing order…':'Dispatch to AI Agent'}<ArrowRight size={17}/></button></form><div className="form-note"><ShieldCheck size={18}/><p>{mode==='demo'?'Interactive sample data. No messages or payments are sent.':'Connected to your database. Provider actions remain recorded intents in this starter.'}</p></div><div className="try-guide"><span>TRY A SCENARIO</span><p><b>Tapal Tea</b> → discounted replacement</p><p><b>Dalda Oil</b> → ready to fulfill</p><p><b>Basmati Rice</b> → no alternative</p><p><b>High risk</b> → human review</p></div></section>
 <section className="panel orders-panel"><div className="section-head"><h2><span className="accent green"/>Orders</h2><span className="refresh-label">{mode==='demo'?'interactive demo':'refreshes every 3s'}</span></div><div className="table-scroll"><table><thead><tr><th>ORDER</th><th>GROCERY ITEM / CUSTOMER</th><th>TOTAL</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody>{data.orders.map(o=><tr key={o.id}><td className="id-cell">{o.display_id||'#'+o.id.slice(0,5)}</td><td className="item-cell"><span>{o.items[0]?.name||'Grocery order'}{o.items.length>1?` +${o.items.length-1}`:''}</span><small>{o.items[0]?.quantity} × · {o.customer_email}</small></td><td className="amount-cell">{money(o.final_total_paisa)}</td><td><span className={'status '+o.status}>{statusLabels[o.status]||o.status}</span></td><td>{o.status==='awaiting_customer'?<button className="action review" aria-label={`Review offer for ${o.display_id||o.id}`} onClick={()=>setModal({kind:'order',id:o.id})}>Review</button>:o.status==='manual_review'?<button className="action audit" aria-label={`Audit ${o.display_id||o.id}`} onClick={()=>setModal({kind:'order',id:o.id})}>Audit</button>:<button className="icon-btn view-btn" aria-label={`View ${o.display_id||o.id}`} onClick={()=>setModal({kind:'order',id:o.id})}><Eye size={15}/></button>}</td></tr>)}</tbody></table>{!data.orders.length&&<div className="empty"><Basket size={30}/><h3>No orders yet</h3><p>Create a grocery order to start the pipeline.</p></div>}</div><div className="table-footer"><span>{data.orders.length} {mode==='live'?'recent':'sample'} orders</span><span>PKR · {mode==='demo'?'Fictional prices':'Catalog prices'}</span></div></section></div>
 <section className="panel activity"><div className="section-head"><h2><span className="accent purple"/>Agent Activity Stream</h2><span className="refresh-label">{mode==='demo'?'SIMULATED':'RECORDED EVENTS'}</span></div><div className="activity-list">{data.events.slice(0,20).map(e=><div className="event" key={e.id}><span className={'event-type '+e.kind}>{e.kind==='offer_email'?'OFFER':e.kind.includes('refund')?'REFUND':e.kind==='fulfillment'?'READY':e.kind.toUpperCase()}</span><p>{e.payload?.text||`${e.kind.replaceAll('_',' ')}${e.payload?.amount_paisa?' · '+money(e.payload.amount_paisa):''}`}</p><time>{new Date(e.created_at).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}</time></div>)}{!data.events.length&&<p className="quiet">Activity appears when the worker processes an order.</p>}</div></section>
 <div className="bottom-note"><Lightning size={13}/>{mode==='demo'?'Demo simulation':'Connected workflow'} · Customer approval required · Refunds shown only as pending</div></main><footer>OrderOps AI · Grocery Order Triage &amp; Resolution · Built with LangGraph + FastAPI</footer>
 {notice&&<div className="toast" role="status"><CheckCircle size={18}/>{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={16}/></button></div>}
 {error&&!modal&&<div className="error-banner" role="alert"><WarningCircle size={18}/>{error}<button onClick={()=>setError('')} aria-label="Dismiss error"><X/></button></div>}
 {modal?.kind==='connect'&&<Modal title="Connect your workspace" onClose={()=>{setModal(null);setError('');}}><p className="modal-copy">Preview with sample groceries, or connect to the FastAPI app serving this dashboard.</p><div className="mode-options"><button className={mode==='demo'?'selected':''} onClick={()=>{setMode('demo');setKey('');setProduct('1');setModal(null);setError('');}}>Demo mode<span>Sample orders · no database needed</span></button><div className="connect-info"><PlugsConnected size={20}/><b>Live database</b><span>FastAPI and the worker must be running.</span></div></div><form onSubmit={connect}><label>ADMIN API KEY<input type="password" aria-label="Admin API key" autoComplete="off" required value={candidateKey} onChange={e=>setCandidateKey(e.target.value)} placeholder="Enter the key from your .env file"/></label><p className="quiet">Used for this session only. Never saved in browser storage.</p>{error&&<p className="form-error" role="alert">{error}</p>}<button className="dispatch" disabled={connecting}>{connecting?'Connecting…':'Connect to API'}<PlugsConnected size={17}/></button></form></Modal>}
 {modal?.kind==='order'&&selectedOrder&&<Modal title={`${selectedOrder.display_id||'#'+selectedOrder.id.slice(0,5)} · ${selectedOrder.status==='manual_review'?'Human review':offer?'Replacement offer':'Order details'}`} onClose={()=>{setModal(null);setError('');}}><p className="modal-copy">{selectedOrder.customer_email} · {selectedOrder.payment_method==='cod'?'Cash on delivery':'Prepaid'}</p>{selectedOrder.items.map((i,n)=><div className="detail-item" key={n}><span>{offer?'Original item':'Grocery item'}</span><strong>{i.name}</strong><small>{i.quantity} × {money(i.unit_price_paisa)}</small></div>)}{offer&&<><div className="detail-item proposed"><span>RESERVED ALTERNATIVE</span><strong>{offer.name}</strong><small>{offer.quantity||selectedOrder.items[0]?.quantity} × {money(offer.unit_price_paisa)} · discounted price</small></div><p className="modal-copy">{mode==='demo'?'Simulate the customer’s explicit decision.':'These controls simulate a customer response using the starter’s recorded offer.'} Acceptance updates the order. Rejection cancels the entire order.</p></>}{selectedOrder.status==='manual_review'&&<p className="audit-warning">Risk score {selectedOrder.risk_score.toFixed(2)}. Inventory stays untouched until you approve. Rejecting starts cancellation.</p>}<div className="order-total"><span>Current order total</span><strong>{money(selectedOrder.final_total_paisa)}</strong></div>{offer&&<div className="order-total"><span>After replacement</span><strong>{money(newTotal)}</strong></div>}{error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-actions">{offer?<><button className="accept" disabled={busy} onClick={()=>act('accept')}>Simulate accept</button><button className="reject" disabled={busy} onClick={()=>act('reject')}>Simulate reject</button></>:selectedOrder.status==='manual_review'?<><button className="accept" disabled={busy} onClick={()=>act('approve')}>Approve order</button><button className="reject" disabled={busy} onClick={()=>act('reject')}>Reject order</button></>:<span className={'status '+selectedOrder.status}>{statusLabels[selectedOrder.status]||selectedOrder.status}</span>}</div></Modal>}
 </>;
}
